import { useState } from "react";
import { ArrowUpRight, ChefHat, ChevronRight, Clock3, Instagram, Mail, Menu, MessageCircle, ShoppingBasket, Sparkles, X } from "lucide-react";

const stories = [
  { number: "01", type: "BELANJA HEMAT", title: "Rp25.000, masih bisa masak apa hari ini?", body: "Rincian belanja pasar pagi, menu sederhana, dan obrolan yang selalu bikin kita merasa tidak sendirian.", tone: "saffron", icon: <ShoppingBasket /> },
  { number: "02", type: "CATATAN DAPUR", title: "Tiga bahan yang selalu menyelamatkan tanggal tua", body: "Bukan resep mahal. Hanya cara-cara kecil untuk membuat meja makan tetap terasa seperti rumah.", tone: "tomato", icon: <ChefHat /> },
  { number: "03", type: "CERITA SEHARI-HARI", title: "Di meja makan, semua orang punya cerita", body: "Tentang keluarga, tetangga, kerja, dan keputusan kecil yang diam-diam membentuk hidup kita.", tone: "leaf", icon: <MessageCircle /> },
];

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [subscribed, setSubscribed] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  return <div className="site-shell">
    <div className="topline"><span>RUMAH · MAKAN · CERITA</span><span>EDISI 01 / 2026</span></div>
    <header className="nav-wrap">
      <a className="brand" href="#atas" onClick={closeMenu} aria-label="Dapur Tanggal Tua"><span className="brand-mark"><ChefHat size={20} strokeWidth={2.4} /></span><span>Dapur<br /><b>Tanggal Tua</b></span></a>
      <nav className={menuOpen ? "nav-links is-open" : "nav-links"}><a href="#cerita" onClick={closeMenu}>Cerita</a><a href="#dapur" onClick={closeMenu}>Dapur</a><a href="#tentang" onClick={closeMenu}>Tentang</a><a className="nav-cta" href="#hubungi" onClick={closeMenu}>Mari ngobrol <ArrowUpRight size={15} /></a></nav>
      <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Tutup menu" : "Buka menu"} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button>
    </header>
    <main id="atas">
      <section className="hero section-pad"><div className="hero-copy"><p className="eyebrow"><span className="dot" /> JURNAL DAPUR & KEHIDUPAN</p><h1>Yang sederhana,<br /><em>sering kali</em><br />paling berharga.</h1><p className="hero-lead">Cerita tentang makan enak, belanja cermat, dan hidup yang tetap hangat—bahkan ketika tanggal tua datang lebih dulu.</p><div className="hero-actions"><a className="button button-dark" href="#cerita">Baca cerita terbaru <ChevronRight size={17} /></a><a className="text-link" href="#tentang">Kenali dapurnya <ArrowUpRight size={15} /></a></div></div><div className="hero-art" aria-label="Ilustrasi meja dapur dengan bahan makanan"><div className="sun-disc" /><div className="art-label">SEADANYA<br /><strong>JADI LUAR BIASA</strong></div><div className="plate plate-one" /><div className="plate plate-two" /><div className="ingredient tomato-shape" /><div className="ingredient leaf-shape" /><div className="ingredient egg-shape" /><div className="bowl-shape"><span /></div><div className="hero-note"><span>01</span><b>Catatan hari ini</b><small>Masak dari yang ada.</small></div></div></section>
      <section className="ticker" aria-label="Topik yang dibahas"><div>MENU SEDERHANA <span>✳</span> CERITA RUMAH <span>✳</span> BELANJA BIJAK <span>✳</span> TETAP MAKAN ENAK <span>✳</span> MENU SEDERHANA <span>✳</span> CERITA RUMAH <span>✳</span></div></section>
      <section className="stories section-pad" id="cerita"><div className="section-heading"><div><p className="eyebrow">01 / PILIHAN EDITOR</p><h2>Cerita terbaru<br /><em>dari meja makan.</em></h2></div><p className="section-intro">Tidak ada yang terlalu kecil untuk diceritakan. Karena dari hal-hal sehari-hari, biasanya kita menemukan alasan untuk terus berjalan.</p></div><div className="story-grid">{stories.map((story) => <article className={`story-card ${story.tone}`} key={story.number}><div className="card-visual"><span className="card-number">{story.number}</span><span className="visual-symbol">{story.icon}</span><span className="card-tag">{story.type}</span></div><div className="card-copy"><h3>{story.title}</h3><p>{story.body}</p><a href="#hubungi" aria-label={`Baca ${story.title}`}>Baca catatan <ArrowUpRight size={16} /></a></div></article>)}</div></section>
      <section className="manifesto section-pad" id="dapur"><div className="manifesto-visual"><div className="stamp">DTT<br /><small>EST. 2026</small></div><div className="big-quote">“</div><p>Masak dari yang ada.<br /><b>Syukuri yang terasa.</b></p></div><div className="manifesto-copy"><p className="eyebrow">02 / FILOSOFI DAPUR</p><h2>Dapur bukan soal<br /><em>sempurna.</em></h2><p>Ini ruang kecil untuk berbagi cara hidup yang lebih jujur: mengolah bahan yang tersedia, bercerita tanpa dibuat-buat, dan menemukan rasa cukup di tengah banyak maunya dunia.</p><div className="principles"><div><span>01</span><b>Otentik</b><small>Foto dan cerita dari keseharian.</small></div><div><span>02</span><b>Praktis</b><small>Ide yang bisa langsung dicoba.</small></div><div><span>03</span><b>Hangat</b><small>Selalu ada ruang untuk ngobrol.</small></div></div></div></section>
      <section className="newsletter section-pad" id="hubungi"><div><p className="eyebrow">03 / SURAT DARI DAPUR</p><h2>Satu cerita kecil,<br /><em>setiap minggu.</em></h2></div><div className="newsletter-side"><p>Dapatkan catatan menu hemat, cerita rumah, dan ide dapur yang tidak menggurui langsung di kotak masuk.</p>{subscribed ? <div className="success-note"><Sparkles size={18} /> Terima kasih. Sampai jumpa di dapur.</div> : <form onSubmit={(e) => { e.preventDefault(); setSubscribed(true); }}><label className="sr-only" htmlFor="email">Alamat email</label><input id="email" type="email" placeholder="alamat@email.com" required /><button type="submit" aria-label="Berlangganan"><ArrowUpRight size={20} /></button></form>}<small><Clock3 size={13} /> Tidak spam. Hanya hal-hal baik.</small></div></section>
    </main>
    <footer className="footer section-pad" id="tentang"><div className="footer-brand"><span className="brand-mark"><ChefHat size={20} /></span><p><b>Dapur Tanggal Tua</b><br />Ruang kecil untuk cerita yang besar rasanya.</p></div><div className="footer-links"><a href="mailto:halo@dapurtanggaltua.id"><Mail size={15} /> halo@dapurtanggaltua.id</a><a href="#cerita"><Instagram size={15} /> Instagram / segera hadir</a><a href="#atas">Kembali ke atas ↑</a></div><div className="footer-bottom"><span>© 2026 Dapur Tanggal Tua</span><span>Dibuat dengan bahan seadanya.</span></div></footer>
  </div>;
}
